flightgoggles_uav_dynamics:
  init_pose: [2.0, 36.0, 1.5, 0.0, 0.0, -0.707, 0.707]
challenge_name: "Challenge Medium"
timeout: 200.0
gate_names: ['Gate1', 'Gate2', 'Gate3', 'Gate4']
gate_width: 0.3
results_location: "results.yaml"

